chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),

]



















# from django.urls import path, re_path


# from .views import ThreadView, InboxView

# app_name = 'chat'
# urlpatterns = [
#     path("", InboxView.as_view()),
#     re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
# ]

coursechat/urls.py
from django.contrib import admin
from django.urls import path, re_path ,include
from django.views.generic import TemplateView
# from youtube import urls as youtube_urls
from django.contrib.auth import views as auth_views
import profiles.views as accounts_views


urlpatterns = [
    # path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='profile/login.html'), name='login'),

    path('chat/', include('chat.urls')),
    path('', include('youtube.urls')),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    # path('hello/', accounts_views.hello, name='home'),

    re_path(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='profile/password_reset.html',
            email_template_name='profile/password_reset_email.html',
            subject_template_name='profile/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='profile/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='profile/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='profile/password_reset_complete.html'),
        name='password_reset_complete'),

    re_path(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='profile/password_change.html'),
        name='password_change'),
    re_path(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='profile/password_change_done.html'),
        name='password_change_done'),
]

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
from django.contrib.auth.decorators import login_required





def index(request):
    return render(request, 'chat/index.html', {})


@login_required(redirect_field_name=None)
def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'user_name': request.user.username,
    })












# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.http import Http404, HttpResponseForbidden
# from django.shortcuts import render
# from django.urls import reverse
# from django.views.generic.edit import FormMixin

# from django.views.generic import DetailView, ListView

# from .forms import ComposeForm
# from .models import Thread, ChatMessage


# class InboxView(LoginRequiredMixin, ListView):
#     template_name = 'chat/inbox.html'
#     def get_queryset(self):
#         return Thread.objects.by_user(self.request.user)


# class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
#     template_name = 'chat/thread.html'
#     form_class = ComposeForm
#     success_url = './'

#     def get_queryset(self):
#         return Thread.objects.by_user(self.request.user)

#     def get_object(self):
#         other_username  = self.kwargs.get("username")
#         obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
#         if obj == None:
#             raise Http404
#         return obj

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['form'] = self.get_form()
#         return context

#     def post(self, request, *args, **kwargs):
#         if not request.user.is_authenticated:
#             return HttpResponseForbidden()
#         self.object = self.get_object()
#         form = self.get_form()
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)

#     def form_valid(self, form):
#         thread = self.get_object()
#         user = self.request.user
#         message = form.cleaned_data.get("message")
#         ChatMessage.objects.create(user=user, thread=thread, message=message)
#         return super().form_valid(form)

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Chat Rooms</title>
</head>

<body>


    What chat room would you like to enter?<br />
    <input id="room-name-input" type="text" size="100" /><br />
    <input id="room-name-submit" type="button" value="Enter" />

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function (e) {
            if (e.keyCode === 13) { // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function (e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>

</html>

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>

    <link rel="stylesheet" href="{% static './Styles/home.css' %}">
    <script src="https://kit.fontawesome.com/a8c305d3e9.js"></script>

</head>
<script src="https://www.youtube.com/iframe_api"></script>

<body>
    
 <h2 class="main-heading">Live CourseChat</h2>
 <div class="card">
     <div class="card__video-container">
        <div id="video-placeholder"></div>
     </div>
     <div class="card__video-info">
         
     </div>
 </div>
<div class="card">
   
    <div class="card__video-info">
            <b></bold><textarea id="chat-log" cols="46" rows="20" ></textarea></b><br />
            <input id="chat-message-input" class="video-join-btn"  type="text" /><br />
            <input id="chat-message-submit" class="video-join-btn" type="button" value="Send" />

    </div>
</div>

</body>
<script>
var roomName = {{ room_name_json }};
var userName = '{{user_name}}';

var player;
// var vdId = 'mSHLO-hE2nI' ;  //comes from youtube_obj.current_url
// https://youtu.be/
function onYouTubeIframeAPIReady() {
player = new YT.Player('video-placeholder', {
width: 600,
height: 400,
videoId: roomName,
playerVars: {
color: 'white',
'autoplay': 1,
'controls': 0,

// playlist: 'taJ60kskkns,FG0fTKAqZ5g'
},
// events: {
// onReady: initialize
// }
});
}


    
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function (e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var updateTime = data['backend_time']
        // console.log(e)
        // console.log(data)
        // console.log('inside the onmessage time is ', updateTime)
        document.querySelector('#chat-log').value += ('@'+ userName + '\n'+ message + '\n\n');
        
        myNewFunction(updateTime);
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) { // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        let time = player.getCurrentTime()
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'time': time,
        }));

        messageInputDom.value = '';
    };




function myNewFunction(newTime){
let currentTime =  player.getCurrentTime() 
console.log('current time')
console.log(currentTime)
console.log('new time')
console.log(newTime)
if (currentTime < newTime){
    player.seekTo(newTime);
}
console.log('after update')
console.log(player.getCurrentTime() )
}

</script>

</html>

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} via {{ chat.user }}</li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script>
// websocket scripts

</script>
{% endblock %}